version = 0.1
[default.deploy.parameters]
stack_name = "mixpanel-proxy-stack"
resolve_s3 = true
s3_prefix = "mixpanel-proxy-stack"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MixpanelToken=\"none\" FrontendUrl=\"none\" Runtime=\"prod\" Region=\"US\" Platform=\"AWS\""
image_repositories = []
